[package]
name = "gazelle"
version = "0.1.0"
edition = "2024"

[features]
default = ["codegen"]
codegen = ["dep:syn", "dep:quote", "dep:proc-macro2"]

[dependencies]
syn = { version = "2", optional = true }
quote = { version = "1", optional = true }
proc-macro2 = { version = "1", optional = true }

[dev-dependencies]
gazelle-macros = { path = "gazelle-macros" }
