[package]
name = "gazelle-core"
version = "0.1.0"
edition = "2024"

[features]
default = []
codegen = ["dep:syn", "dep:quote", "dep:proc-macro2"]

[dependencies]
syn = { version = "2", optional = true }
quote = { version = "1", optional = true }
proc-macro2 = { version = "1", optional = true }
